//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectriqueMobility.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class produit
    {
        public int id { get; set; }
        public int une_categorie_id { get; set; }
        public string designation { get; set; }
        public string detail { get; set; }
        public decimal prix { get; set; }
        public string photo { get; set; }
    
        public virtual categorie categorie { get; set; }
    }
}
